Repository DSC-JSS-NOIDA/foss-events, pull requests merged in 2021-03, with the labels that each got.

#160 Added_feature_of_Background_UI_animation_with_particle_JS#158
  .vscode/settings.json
  Frontend/js/app.js
  Frontend/js/jquery-3.2.1.min.js
  Frontend/js/particle.js
  Frontend/style.css
  index.html
Labels: GSSOC21, Level2

#219 changes in appearence of title
  Frontend/style.css
Labels: GSSOC21, Level0, enhancement

#221 Changed the placeholder text of the search bar
  index.html
Labels: GSSOC21, Level0

#253 Fixed the search bar, and made the text more appropriate
  index.html
Labels: GSSOC21, Level0
