Repository DSC-JSS-NOIDA/foss-events, pull requests merged in 2021-05, with the labels that each got.

#350 Improved Search Bar
  Frontend/style.css
  index.html
Labels: GSSOC21, Level1

#352 Made the search bar responsive.
  Frontend/style.css
Labels: GSSOC21, Level1

#356 Adding More Open Source Events
  Frontend/data/events.json
Labels: GSSOC21, Level1

#371 Update README.md for the Integration branch
  README.md
Labels: GSSOC21, Level1

#363 fixes search icon
  index.html
Labels: GSSOC21, Level0

#377 Enhancement: Favicon
  Frontend/data/img/favicon.jpeg
  feedback.html
  index.html
Labels: GSSOC21, Level1

#337 Message displayed
  Frontend/js/getEvent.js
  Frontend/style.css
Labels: GSSOC21, Level1

#343 Validation added
  index.html
Labels: GSSOC21, Level1

#379 added eslint setup and prettier code
  .eslintrc.js
  package.json
Labels: GSSOC21, Level3

#382 Update index. html by adding clock
  index.html
Labels: GSSOC21, Level1

#361 Added 3 Social Links
  Frontend/style.css
  index.html
Labels: GSSOC21, Level1, enhancement

#390 about us section
  Frontend/data/img/About us page-bro.svg
  Frontend/style.css
  index.html
  package-lock.json
Labels: GSSOC21, Level1

#392 hover effect on event card
  Frontend/style.css
  index.html
Labels: GSSOC21, Level1

#402 Fixed issue 399
  Frontend/data/events.json
Labels: GSSOC21, Level0
